website/views.py
from flask import Blueprint, render_template,request,flash
from flask_login import current_user
from .models import *

views=Blueprint('views',__name__)

@views.route('/')
@views.route('/home')
def home():
    return render_template('home.html',user=current_user)

@views.route('/clothes')
def clothes():
    page=request.args.get('page',1,type=int)
    sort=request.args.get('sort','oldest',type=str)
    productType='clothes'
    filteredProducts=getFilteredProducts(productType)
    sortedFilteredProducts=getSortedProducts(sort,page,filteredProducts)
    return render_template('clothes.html',user=current_user,products=sortedFilteredProducts)

@views.route('/perfumes')
def perfumes():
    page=request.args.get('page',1,type=int)
    sort=request.args.get('sort','oldest',type=str)
    productType='perfumes'
    filteredProducts=getFilteredProducts(productType)
    sortedFilteredProducts=getSortedProducts(sort,page,filteredProducts)
    return render_template('perfumes.html',user=current_user,products=sortedFilteredProducts)

@views.route('/handbags')
def handbags():
    page=request.args.get('page',1,type=int)
    sort=request.args.get('sort','oldest',type=str)
    productType='handbags'
    filteredProducts=getFilteredProducts(productType)
    sortedFilteredProducts=getSortedProducts(sort,page,filteredProducts)
    return render_template('handbags.html',user=current_user,products=sortedFilteredProducts)

@views.route('/viewProduct')
def viewProduct():
    productId=request.args.get('id',1,type=int)
    currentColor=request.args.get('color','none',type=str)
    product=Product.query.join(Product.product_configs).filter(Product.id==productId).first()
    availableColors=[]
    if product.type=='clothes':
        for config in product.product_configs:
            if config.quantity>0:
                if config.color not in availableColors:
                    availableColors.append(config.color)
    return render_template('viewProduct.html',user=current_user,product=product,currentColor=currentColor,availableColors=availableColors)

def getSortedProducts(sort,page,products):
    if sort=='oldest':
        sortedProducts=products.order_by(Product.id.asc()).paginate(page=page,per_page=8)
    elif sort=='newest':
        sortedProducts=products.order_by(Product.id.desc()).paginate(page=page,per_page=8)
    elif sort=='price-low-high':
        sortedProducts=products.order_by(Product.price.asc()).paginate(page=page,per_page=8)
    elif sort=='price-high-low':
        sortedProducts=products.order_by(Product.price.desc()).paginate(page=page,per_page=8)

    return sortedProducts

def getFilteredProducts(productType):
    if productType=='clothes':
        filterSizes=getFilterSizes()
        filteredProducts=Product.query.filter(Product.type==productType,Product.product_configs.any(Product_config.size.in_(filterSizes)),Product.product_configs.any(Product_config.quantity>0))
    if productType=='perfumes':
        filteredProducts=Product.query.filter(Product.type==productType,Product.product_configs.any(Product_config.quantity>0))
    if productType=='handbags':
        filteredProducts=Product.query.filter(Product.type==productType,Product.product_configs.any(Product_config.quantity>0))
    
    return filteredProducts

def getFilterSizes():
    filterSizes=[]
    if request.args.get('xs','false',type=str)=='true':
        filterSizes.append('xs')
    if request.args.get('s','false',type=str)=='true':
        filterSizes.append('s')
    if request.args.get('m','false',type=str)=='true':
        filterSizes.append('m')
    if request.args.get('l','false',type=str)=='true':
        filterSizes.append('l')
    if request.args.get('xl','false',type=str)=='true':
        filterSizes.append('xl')
    if filterSizes==[]:
        filterSizes=['xs','s','m','l','xl']
    return filterSizes

website/templates/clothes.html
{% extends 'base.html' %}
{% block title %}Одежда{% endblock %}

{% block intro_title %}Одежда{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg">
    <div class="container ">
        <a href="/" class="navbar-brand">
            <img src="https://ik.imagekit.io/fdmzvitxq/azhustore/tr:bl-80/logo.png" class="logo" height='70' alt="">
        </a>



        <button class='navbar-toggler custom-toggler' type='button' data-bs-toggle='collapse'
            data-bs-target='#navbarContent' aria-controls='navbarContent' aria-expanded='false'>
            <span class='navbar-toggler-icon'></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav mr-auto mb-2 w-100 nav-justified" data-mdb-right="true">
                <li class="nav-item">
                    <a href="/" class='nav-link'>Главная</a>
                </li>
                <li class="nav-item">
                    <a href="/clothes" class='nav-link active'>Одежда</a>
                </li>
                <li class="nav-item">
                    <a href="/handbags" class='nav-link'>Сумки</a>
                </li>
                <li class="nav-item">
                    <a href="/perfumes" class='nav-link'>Парфюмы</a>
                </li>
                <li class="nav-item">
                    <a href="https://www.instagram.com/azhu.store/" id="icon" class='nav-link'><i
                            class="bi bi-instagram"></i></a>
                </li>
                <li class="nav-item">
                    <a href="/cart" class='nav-link' id="icon"><i class="bi bi-bag"></i></a>
                </li>
                <li class="nav-item">
                    <a href="/history" class='nav-link' id="icon"><i class="bi bi-clock-history"></i></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="/logout" class='nav-link' id="icon"><i class="bi bi-box-arrow-left"
                            style="color: red;"></i></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="/sign" class='nav-link' id="icon"><i style="color: #16DE16;"
                            class="bi bi-box-arrow-in-right"></i></a>
                </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
{% endblock %}

{% block intro_type %}clothes{% endblock %}

{% block intro_content_type %}goods{% endblock %}

{% block content %}
<section class="tovary">
    <div class="container">
        
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            <i class="bi bi-funnel-fill"></i>
        </button>
        
        <div id="collapseExample" class="collapse">
          <div class="card card-body ">
            <form>
                <select name="sort" id="sort" class="form-select mb-2">
                    <option value="oldest" {% if request.args.get('sort','oldest')=='oldest' %} selected {% endif %}>Сортировка</option>
                    <option value="price-low-high" {% if request.args.get('sort','oldest')=='price-low-high'%} selected {% endif %}>ЦЕНА: $–$$$</option>
                    <option value="price-high-low" {% if request.args.get('sort','oldest')=='price-high-low' %} selected {% endif %}>ЦЕНА: $$$–$</option>
                    <option value="newest" {% if request.args.get('sort','oldest')=='newest' %} selected {% endif %}>Новые</option>
                </select>
  
                <p>Размеры: </p>
                <div class="form-check form-check-inline mb-2">
                    <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value=true name="xs" {% if request.args.get('xs','false')=='true' %} checked {% endif %}>
                    <label class="form-check-label" for="inlineCheckbox1">XS</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value='true' name="s" {% if request.args.get('s','false')=='true' %} checked {% endif %}>
                    <label class="form-check-label" for="inlineCheckbox2">S</label>
                </div>
                <div class="form-check form-check-inline mb-2">
                    <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value='true' name="m" {% if request.args.get('m','false')=='true' %} checked {% endif %}>
                    <label class="form-check-label" for="inlineCheckbox3">M</label>
                </div>
                <div class="form-check form-check-inline mb-2">
                    <input class="form-check-input" type="checkbox" id="inlineCheckbox4" value='true' name="l" {% if request.args.get('l','false')=='true' %} checked {% endif %}>
                    <label class="form-check-label" for="inlineCheckbox4">L</label>
                </div>
                <div class="form-check form-check-inline mb-2">
                    <input class="form-check-input" type="checkbox" id="inlineCheckbox5" value='true' name="xl" {% if request.args.get('xl','false')=='true' %} checked {% endif %}>
                    <label class="form-check-label" for="inlineCheckbox5">XL</label>
                </div>
                <br>
                <button type="submit" class="btn btn-outline-info"><i class="bi bi-arrow-right"></i></button>
            </form>
          </div>
        </div>

        <div class="tovary__row row justify-content-around" id="products">
            {% for product in products.items %}
            <div class="col-lg-3 col-6 p-1">
                <div class="card card-good" onclick='window.location.href = "{{ url_for('views.viewProduct', id=product.id) }} ";'>
                    <img src="{{ product.image }}" alt="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">
                            <div class="tovary__cost">{{ product.price }} Tg</div>
                            <div class="tovary__sizes">
                                {% set sizes=['xs','s','m','l','xl'] %}
                                {% for size in sizes %}
                                    {% set quantity=namespace(value=0) %}
                                    {% for config in product.product_configs %}

                                        {% if config.size==size %}
                                            {% set quantity.value=quantity.value+config.quantity %}
                                        {%endif%}
                                        
                                    {% endfor %}
                                    {{size}}: {{quantity.value}}
                                {% endfor %}
                            </div></p>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
        <div class="d-flex justify-content-center">
            {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if products.page == page_num %}
                    <a class="btn btn-info m-3" href="{{ url_for('views.clothes', page=page_num,sort=request.args.get('sort','oldest'),xs=request.args.get('xs','false'),s=request.args.get('s','false'),m=request.args.get('m','false'),l=request.args.get('l','false'),xl=request.args.get('xl','false')) }}">{{ page_num }}</a>
                    {% else %}
                    <a class="btn btn-outline-info m-3" href="{{ url_for('views.clothes', page=page_num,sort=request.args.get('sort','oldest'),xs=request.args.get('xs','false'),s=request.args.get('s','false'),m=request.args.get('m','false'),l=request.args.get('l','false'),xl=request.args.get('xl','false')) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                <p style="transform: translate(0,60%);">...</p>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

{% block footer_type %}goods{% endblock %}

{% block footer_logo %}logo-dark.png{% endblock %}

website/templates/handbags.html
{% extends 'base.html' %}
{% block title %}Одежда{% endblock %}

{% block intro_title %}Одежда{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg">
    <div class="container ">
        <a href="/" class="navbar-brand">
            <img src="https://ik.imagekit.io/fdmzvitxq/azhustore/tr:bl-80/logo.png" class="logo" height='70' alt="">
        </a>



        <button class='navbar-toggler custom-toggler' type='button' data-bs-toggle='collapse'
            data-bs-target='#navbarContent' aria-controls='navbarContent' aria-expanded='false'>
            <span class='navbar-toggler-icon'></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav mr-auto mb-2 w-100 nav-justified" data-mdb-right="true">
                <li class="nav-item">
                    <a href="/" class='nav-link'>Главная</a>
                </li>
                <li class="nav-item">
                    <a href="/clothes" class='nav-link '>Одежда</a>
                </li>
                <li class="nav-item">
                    <a href="/handbags" class='nav-link active'>Сумки</a>
                </li>
                <li class="nav-item">
                    <a href="/perfumes" class='nav-link'>Парфюмы</a>
                </li>
                <li class="nav-item">
                    <a href="https://www.instagram.com/azhu.store/" id="icon" class='nav-link'><i
                            class="bi bi-instagram"></i></a>
                </li>
                <li class="nav-item">
                    <a href="/cart" class='nav-link' id="icon"><i class="bi bi-bag"></i></a>
                </li>
                <li class="nav-item">
                    <a href="/history" class='nav-link' id="icon"><i class="bi bi-clock-history"></i></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="/logout" class='nav-link' id="icon"><i class="bi bi-box-arrow-left"
                            style="color: red;"></i></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="/sign" class='nav-link' id="icon"><i style="color: #16DE16;"
                            class="bi bi-box-arrow-in-right"></i></a>
                </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
{% endblock %}

{% block intro_type %}clothes{% endblock %}

{% block intro_content_type %}goods{% endblock %}

{% block content %}
<section class="tovary">
    <div class="container">
        
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            <i class="bi bi-funnel-fill"></i>
        </button>
        
        <div id="collapseExample" class="collapse">
          <div class="card card-body ">
            <form>
                <select name="sort" id="sort" class="form-select mb-2">
                    <option value="oldest" {% if request.args.get('sort','oldest')=='oldest' %} selected {% endif %}>Сортировка</option>
                    <option value="price-low-high" {% if request.args.get('sort','oldest')=='price-low-high'%} selected {% endif %}>ЦЕНА: $–$$$</option>
                    <option value="price-high-low" {% if request.args.get('sort','oldest')=='price-high-low' %} selected {% endif %}>ЦЕНА: $$$–$</option>
                    <option value="newest" {% if request.args.get('sort','oldest')=='newest' %} selected {% endif %}>Новые</option>
                </select>
  
                <br>
                <button type="submit" class="btn btn-outline-info"><i class="bi bi-arrow-right"></i></button>
            </form>
          </div>
        </div>

        <div class="tovary__row row justify-content-around" id="products">
            {% for product in products.items %}
            <div class="col-lg-3 col-6 p-1">
                <div class="card card-good">
                    <img src="{{ product.image }}" alt="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">
                            <div class="tovary__cost">{{ product.price }} Tg</div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
        <div class="d-flex justify-content-center">
            {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if products.page == page_num %}
                    <a class="btn btn-info m-3" href="{{ url_for('views.clothes', page=page_num,sort=request.args.get('sort','oldest'),xs=request.args.get('xs','false'),s=request.args.get('s','false'),m=request.args.get('m','false'),l=request.args.get('l','false'),xl=request.args.get('xl','false')) }}">{{ page_num }}</a>
                    {% else %}
                    <a class="btn btn-outline-info m-3" href="{{ url_for('views.clothes', page=page_num,sort=request.args.get('sort','oldest'),xs=request.args.get('xs','false'),s=request.args.get('s','false'),m=request.args.get('m','false'),l=request.args.get('l','false'),xl=request.args.get('xl','false')) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                <p style="transform: translate(0,60%);">...</p>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

{% block footer_type %}goods{% endblock %}

{% block footer_logo %}logo-dark.png{% endblock %}

website/templates/home.html
{% extends 'base.html' %}
{% block title %}Главная{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg">
    <div class="container ">
        <a href="/" class="navbar-brand">
            <img src="https://ik.imagekit.io/fdmzvitxq/azhustore/tr:bl-80/logo.png" class="logo" height='70' alt="">
        </a>



        <button class='navbar-toggler custom-toggler' type='button' data-bs-toggle='collapse'
            data-bs-target='#navbarContent' aria-controls='navbarContent' aria-expanded='false'>
            <span class='navbar-toggler-icon'></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav mr-auto mb-2 w-100 nav-justified" data-mdb-right="true">
                <li class="nav-item">
                    <a href="/" class='nav-link active'>Главная</a>
                </li>
                <li class="nav-item">
                    <a href="/clothes" class='nav-link'>Одежда</a>
                </li>
                <li class="nav-item">
                    <a href="/handbags" class='nav-link'>Сумки</a>
                </li>
                <li class="nav-item">
                    <a href="/perfumes" class='nav-link'>Парфюмы</a>
                </li>
                <li class="nav-item">
                    <a href="https://www.instagram.com/azhu.store/" id="icon" class='nav-link'><i
                            class="bi bi-instagram"></i></a>
                </li>
                <li class="nav-item">
                    <a href="/cart" class='nav-link' id="icon"><i class="bi bi-bag"></i></a>
                </li>
                <li class="nav-item">
                    <a href="/history" class='nav-link' id="icon"><i class="bi bi-clock-history"></i></a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="/logout" class='nav-link' id="icon"><i
                                class="bi bi-box-arrow-left" style="color: red;"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="/sign" class='nav-link' id="icon"><i style="color: #16DE16;" class="bi bi-box-arrow-in-right"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
{% endblock %}

{% block intro_type %}{% endblock %}

{% block content %}
<section class="about">
    <div class="container">
        <div class="about__content col">
            <img src="https://ik.imagekit.io/fdmzvitxq/azhustore/tr:bl-80/quote.png" alt="" class="img-fluid col-1">
            <p class="about__text" style="font-size:2vw;">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In arcu nibh vitae amet. Ipsum, pharetra
                donec ornare velit. Id at quisque accumsan risus ac ipsum ut. Sit elit, facilisi proin non malesuada
                sociis tristique. Viverra augue lorem ut quisque quam tortor
            </p>
            <p class="about__title" style="font-size:3vw;">
                Товары:
            </p>
        </div>


        <div class="products row justify-content-around">
            <a class="products__item col-3" href="odezhda.php">
                <img src="https://ik.imagekit.io/fdmzvitxq/azhustore/tr:bl-80/clothes.jpg" class="img-fluid" alt="">

                <div class="products__title text-justify">Одежда</div>
            </a>
            <a class="products__item col-3" href="sumki.php">
                <img src="https://ik.imagekit.io/fdmzvitxq/azhustore/tr:bl-80/handbags.jpg" class="img-fluid" alt="">

                <div class="products__title text-justify">Сумки</div>
            </a>
            <a class="products__item col-3" href="perfumes.php">
                <img src="https://ik.imagekit.io/fdmzvitxq/azhustore/tr:bl-80/perfumes.jpg" class="img-fluid" alt="">

                <div class="products__title text-justify">Парфюмы</div>
            </a>
        </div>


    </div>
</section>
{% endblock %}

website/templates/perfumes.html
{% extends 'base.html' %}
{% block title %}Одежда{% endblock %}

{% block intro_title %}Одежда{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg">
    <div class="container ">
        <a href="/" class="navbar-brand">
            <img src="https://ik.imagekit.io/fdmzvitxq/azhustore/tr:bl-80/logo.png" class="logo" height='70' alt="">
        </a>



        <button class='navbar-toggler custom-toggler' type='button' data-bs-toggle='collapse'
            data-bs-target='#navbarContent' aria-controls='navbarContent' aria-expanded='false'>
            <span class='navbar-toggler-icon'></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav mr-auto mb-2 w-100 nav-justified" data-mdb-right="true">
                <li class="nav-item">
                    <a href="/" class='nav-link'>Главная</a>
                </li>
                <li class="nav-item">
                    <a href="/clothes" class='nav-link '>Одежда</a>
                </li>
                <li class="nav-item">
                    <a href="/handbags" class='nav-link'>Сумки</a>
                </li>
                <li class="nav-item">
                    <a href="/perfumes" class='nav-link active' >Парфюмы</a>
                </li>
                <li class="nav-item">
                    <a href="https://www.instagram.com/azhu.store/" id="icon" class='nav-link'><i
                            class="bi bi-instagram"></i></a>
                </li>
                <li class="nav-item">
                    <a href="/cart" class='nav-link' id="icon"><i class="bi bi-bag"></i></a>
                </li>
                <li class="nav-item">
                    <a href="/history" class='nav-link' id="icon"><i class="bi bi-clock-history"></i></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="/logout" class='nav-link' id="icon"><i class="bi bi-box-arrow-left"
                            style="color: red;"></i></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="/sign" class='nav-link' id="icon"><i style="color: #16DE16;"
                            class="bi bi-box-arrow-in-right"></i></a>
                </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
{% endblock %}

{% block intro_type %}clothes{% endblock %}

{% block intro_content_type %}goods{% endblock %}

{% block content %}
<section class="tovary">
    <div class="container">
        
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            <i class="bi bi-funnel-fill"></i>
        </button>
        
        <div id="collapseExample" class="collapse">
          <div class="card card-body ">
            <form>
                <select name="sort" id="sort" class="form-select mb-2">
                    <option value="oldest" {% if request.args.get('sort','oldest')=='oldest' %} selected {% endif %}>Сортировка</option>
                    <option value="price-low-high" {% if request.args.get('sort','oldest')=='price-low-high'%} selected {% endif %}>ЦЕНА: $–$$$</option>
                    <option value="price-high-low" {% if request.args.get('sort','oldest')=='price-high-low' %} selected {% endif %}>ЦЕНА: $$$–$</option>
                    <option value="newest" {% if request.args.get('sort','oldest')=='newest' %} selected {% endif %}>Новые</option>
                </select>
  
                <br>
                <button type="submit" class="btn btn-outline-info"><i class="bi bi-arrow-right"></i></button>
            </form>
          </div>
        </div>

        <div class="tovary__row row justify-content-around" id="products">
            {% for product in products.items %}
            <div class="col-lg-3 col-6 p-1">
                <div class="card card-good">
                    <img src="{{ product.image }}" alt="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">
                            <div class="tovary__cost">{{ product.price }} Tg</div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
        <div class="d-flex justify-content-center">
            {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if products.page == page_num %}
                    <a class="btn btn-info m-3" href="{{ url_for('views.clothes', page=page_num,sort=request.args.get('sort','oldest'),xs=request.args.get('xs','false'),s=request.args.get('s','false'),m=request.args.get('m','false'),l=request.args.get('l','false'),xl=request.args.get('xl','false')) }}">{{ page_num }}</a>
                    {% else %}
                    <a class="btn btn-outline-info m-3" href="{{ url_for('views.clothes', page=page_num,sort=request.args.get('sort','oldest'),xs=request.args.get('xs','false'),s=request.args.get('s','false'),m=request.args.get('m','false'),l=request.args.get('l','false'),xl=request.args.get('xl','false')) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                <p style="transform: translate(0,60%);">...</p>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

{% block footer_type %}goods{% endblock %}

{% block footer_logo %}logo-dark.png{% endblock %}

website/templates/reset-password.html
{% extends 'base.html' %}
{% block title %}Сброс пароля{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand">
    <div class="container">
        

        <ul class="navbar-nav mr-auto mb-2 w-100 nav-justified" data-mdb-right="true">

                <li class="nav-item mr-0">
                    <a href="index.php" class="nav-link active"></a>
                </li>
                
        </ul>
        

    </div>
</nav>
{% endblock %}

{% block intro_type %}details{% endblock %}

{% block intro_content_type %}goods{% endblock %}

{% block intro_title %}{% endblock %}

{% block content %}
<section class="sign">
    <div class="container ">
        <div class=" py-5 align-middle">
            <a class="row justify-content-center">
                <img src="../static/images/logo.png" class="col-3" alt="">
            </a>
            
            

            <div class="tabs__body align-baseline">
                <a href="/sign" class="link-info" style="font-size: 20px; margin-left: 20px;"><i class="bi bi-arrow-left"></i></a>
                <div id="tab_01" class="tabs__block tabs__block-active">
                    <form class="" method="POST">
                        <div class="form-group mt-3">
                            <label for="exampleInputName1"  class="input__label">Новый пароль</label>
                            <input type="text" name="password" class="form-control form-control-lg" id="exampleInputName1" placeholder="Введите пароль">
                        </div>
                        
                        <button type="submit" class="btn btn-primary border-0 mt-4 btn-lg" style="background-color: #686da1;">Сбросить пароль</button>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

website/templates/reset.html
{% extends 'base.html' %}
{% block title %}Сброс пароля{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand">
    <div class="container">
        

        <ul class="navbar-nav mr-auto mb-2 w-100 nav-justified" data-mdb-right="true">

                <li class="nav-item mr-0">
                    <a href="index.php" class="nav-link active"></a>
                </li>
                
        </ul>
        

    </div>
</nav>
{% endblock %}

{% block intro_type %}details{% endblock %}

{% block intro_content_type %}goods{% endblock %}

{% block intro_title %}{% endblock %}

{% block content %}
<section class="sign">
    <div class="container ">
        <div class=" py-5 align-middle">
            <a class="row justify-content-center">
                <img src="../static/images/logo.png" class="col-3" alt="">
            </a>
            
            

            <div class="tabs__body align-baseline">
                <a href="/sign" class="link-info" style="font-size: 20px; margin-left: 20px;"><i class="bi bi-arrow-left"></i></a>
                <div id="tab_01" class="tabs__block tabs__block-active">
                    <form class="" method="POST">
                        <div class="form-group mt-3">
                            <label for="exampleInputName1"  class="input__label">Почта</label>
                            <input type="text" name="email" class="form-control form-control-lg" id="exampleInputName1" placeholder="Введите вашу почту">
                        </div>
                        
                        <button type="submit" class="btn btn-primary border-0 mt-4 btn-lg" style="background-color: #686da1;">Сбросить пароль</button>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}